### ISSUE TITLE
Kindly state the compatibilty range

### ISSUE THREAD

**Issue by dawoodjee** [jvfiel/RoleModuleVisibility#1]
It'll be useful to someone to know that their erpnext version is compatible. We'll need to track this and update accordingly.

**Comment by jvfiel** [comment]
Hello @adam-je when I made this it was v7x I haven't tried this for v8x yet. Will let you know

**Comment by dawoodjee** [comment]
Noted​ with thanks

**Comment by jvfiel** [comment]
You're welcome!
